// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go

export type Error = string;
export interface ErrorResponse {
  error: Error;
}
/**
 * Authorization errors.
 */
export const ErrCycleWrongBrand: Error = "cycle does not belong to users brand";
/**
 * Authorization errors.
 */
export const ErrColorwaySizeAssetWrongBrand: Error = "colorway_size_asset does not belong to users brand";
