// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go

export type Error = string;
export interface ErrorResponse {
  error: Error;
}
/**
 * Authorization errors.
 */
export const ErrCycleWrongBrand = any;
/**
 * Authorization errors.
 */
export const ErrColorwaySizeAssetWrongBrand = any;
