// Code generated by tygo. DO NOT EDIT.
import * as bookapp from "../bookstore"

//////////
// source: base.go

export interface Base {
  name: string;
}

//////////
// source: base2.go

export interface Base2 {
  id: any;
}

//////////
// source: base3.go

export interface Base3 {
  class: string;
  level: number /* int */;
}

//////////
// source: other.go

export interface Other extends Base, Base2, Partial<Base3>, bookapp.Book, bookapp.TextBook {
  otherWithBase: Base;
  otherWithBase2: Base2;
  otherValue: string;
  author: bookapp.AuthorWithInheritance;
}
