// Code generated by tygo. DO NOT EDIT.

//////////
// source: client.go

/**
 * A Client is an HTTP client. Its zero value ([DefaultClient]) is a
 * usable client that uses [DefaultTransport].
 * The [Client.Transport] typically has internal state (cached TCP
 * connections), so Clients should be reused instead of created as
 * needed. Clients are safe for concurrent use by multiple goroutines.
 * A Client is higher-level than a [RoundTripper] (such as [Transport])
 * and additionally handles HTTP details such as cookies and
 * redirects.
 * When following redirects, the Client will forward all headers set on the
 * initial [Request] except:
 *   - when forwarding sensitive headers like "Authorization",
 *     "WWW-Authenticate", and "Cookie" to untrusted targets.
 *     These headers will be ignored when following a redirect to a domain
 *     that is not a subdomain match or exact match of the initial domain.
 *     For example, a redirect from "foo.com" to either "foo.com" or "sub.foo.com"
 *     will forward the sensitive headers, but a redirect to "bar.com" will not.
 *   - when forwarding the "Cookie" header with a non-nil cookie Jar.
 *     Since each redirect may mutate the state of the cookie jar,
 *     a redirect may possibly alter a cookie set in the initial request.
 *     When forwarding the "Cookie" header, any mutated cookies will be omitted,
 *     with the expectation that the Jar will insert those mutated cookies
 *     with the updated values (assuming the origin matches).
 *     If Jar is nil, the initial cookies are forwarded without change.
 */
export interface Client {
  /**
   * Transport specifies the mechanism by which individual
   * HTTP requests are made.
   * If nil, DefaultTransport is used.
   */
  Transport: RoundTripper;
  /**
   * CheckRedirect specifies the policy for handling redirects.
   * If CheckRedirect is not nil, the client calls it before
   * following an HTTP redirect. The arguments req and via are
   * the upcoming request and the requests made already, oldest
   * first. If CheckRedirect returns an error, the Client's Get
   * method returns both the previous Response (with its Body
   * closed) and CheckRedirect's error (wrapped in a url.Error)
   * instead of issuing the Request req.
   * As a special case, if CheckRedirect returns ErrUseLastResponse,
   * then the most recent response is returned with its body
   * unclosed, along with a nil error.
   * If CheckRedirect is nil, the Client uses its default policy,
   * which is to stop after 10 consecutive requests.
   */
  CheckRedirect: any;
  /**
   * Jar specifies the cookie jar.
   * The Jar is used to insert relevant cookies into every
   * outbound Request and is updated with the cookie values
   * of every inbound Response. The Jar is consulted for every
   * redirect that the Client follows.
   * If Jar is nil, cookies are only sent if they are explicitly
   * set on the Request.
   */
  Jar: CookieJar;
  /**
   * Timeout specifies a time limit for requests made by this
   * Client. The timeout includes connection time, any
   * redirects, and reading the response body. The timer remains
   * running after Get, Head, Post, or Do return and will
   * interrupt reading of the Response.Body.
   * A Timeout of zero means no timeout.
   * The Client cancels requests to the underlying Transport
   * as if the Request's Context ended.
   * For compatibility, the Client will also use the deprecated
   * CancelRequest method on Transport if found. New
   * RoundTripper implementations should use the Request's Context
   * for cancellation instead of implementing CancelRequest.
   */
  Timeout: number /* time in nanoseconds (time.Duration) */;
}
/**
 * RoundTripper is an interface representing the ability to execute a
 * single HTTP transaction, obtaining the [Response] for a given [Request].
 * A RoundTripper must be safe for concurrent use by multiple
 * goroutines.
 */
export type RoundTripper = any;

//////////
// source: cookie.go

/**
 * A Cookie represents an HTTP cookie as sent in the Set-Cookie header of an
 * HTTP response or the Cookie header of an HTTP request.
 * See https://tools.ietf.org/html/rfc6265 for details.
 */
export interface Cookie {
  Name: string;
  Value: string;
  Quoted: boolean; // indicates whether the Value was originally quoted
  Path: string; // optional
  Domain: string; // optional
  Expires: any /* time.Time */; // optional
  RawExpires: string; // for reading cookies only
  /**
   * MaxAge=0 means no 'Max-Age' attribute specified.
   * MaxAge<0 means delete cookie now, equivalently 'Max-Age: 0'
   * MaxAge>0 means Max-Age attribute present and given in seconds
   */
  MaxAge: number /* int */;
  Secure: boolean;
  HttpOnly: boolean;
  SameSite: SameSite;
  Partitioned: boolean;
  Raw: string;
  Unparsed: string[]; // Raw text of unparsed attribute-value pairs
}
/**
 * SameSite allows a server to define a cookie attribute making it impossible for
 * the browser to send this cookie along with cross-site requests. The main
 * goal is to mitigate the risk of cross-origin information leakage, and provide
 * some protection against cross-site request forgery attacks.
 * See https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00 for details.
 */
export type SameSite = number /* int */;
export const SameSiteDefaultMode: SameSite = 0 + 1;
export const SameSiteLaxMode: SameSite = 1 + 1;
export const SameSiteStrictMode: SameSite = 2 + 1;
export const SameSiteNoneMode: SameSite = 3 + 1;

//////////
// source: csrf.go

/**
 * CrossOriginProtection implements protections against [Cross-Site Request
 * Forgery (CSRF)] by rejecting non-safe cross-origin browser requests.
 * Cross-origin requests are currently detected with the [Sec-Fetch-Site]
 * header, available in all browsers since 2023, or by comparing the hostname of
 * the [Origin] header with the Host header.
 * The GET, HEAD, and OPTIONS methods are [safe methods] and are always allowed.
 * It's important that applications do not perform any state changing actions
 * due to requests with safe methods.
 * Requests without Sec-Fetch-Site or Origin headers are currently assumed to be
 * either same-origin or non-browser requests, and are allowed.
 * The zero value of CrossOriginProtection is valid and has no trusted origins
 * or bypass patterns.
 * [Sec-Fetch-Site]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site
 * [Origin]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
 * [Cross-Site Request Forgery (CSRF)]: https://developer.mozilla.org/en-US/docs/Web/Security/Attacks/CSRF
 * [safe methods]: https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP
 */
export interface CrossOriginProtection {
}

//////////
// source: filetransport.go


//////////
// source: fs.go

/**
 * A Dir implements [FileSystem] using the native file system restricted to a
 * specific directory tree.
 * While the [FileSystem.Open] method takes '/'-separated paths, a Dir's string
 * value is a directory path on the native file system, not a URL, so it is separated
 * by [filepath.Separator], which isn't necessarily '/'.
 * Note that Dir could expose sensitive files and directories. Dir will follow
 * symlinks pointing out of the directory tree, which can be especially dangerous
 * if serving from a directory in which users are able to create arbitrary symlinks.
 * Dir will also allow access to files and directories starting with a period,
 * which could expose sensitive directories like .git or sensitive files like
 * .htpasswd. To exclude files with a leading period, remove the files/directories
 * from the server or create a custom FileSystem implementation.
 * An empty Dir is treated as ".".
 */
export type Dir = string;
/**
 * A FileSystem implements access to a collection of named files.
 * The elements in a file path are separated by slash ('/', U+002F)
 * characters, regardless of host operating system convention.
 * See the [FileServer] function to convert a FileSystem to a [Handler].
 * This interface predates the [fs.FS] interface, which can be used instead:
 * the [FS] adapter function converts an fs.FS to a FileSystem.
 */
export type FileSystem = any;
/**
 * A File is returned by a [FileSystem]'s Open method and can be
 * served by the [FileServer] implementation.
 * The methods should behave the same as those on an [*os.File].
 */
export type File = 
    any /* io.Closer */ &
    any /* io.Reader */ &
    any /* io.Seeker */;

//////////
// source: h2_bundle.go

export const WSAECONNABORTED = 10053;
export const WSAECONNRESET = 10054;
export type I = any;

//////////
// source: header.go

/**
 * A Header represents the key-value pairs in an HTTP header.
 * The keys should be in canonical form, as returned by
 * [CanonicalHeaderKey].
 */
export type Header = { [key: string]: string[]};

//////////
// source: http.go

/**
 * Protocols is a set of HTTP protocols.
 * The zero value is an empty set of protocols.
 * The supported protocols are:
 *   - HTTP1 is the HTTP/1.0 and HTTP/1.1 protocols.
 *     HTTP1 is supported on both unsecured TCP and secured TLS connections.
 *   - HTTP2 is the HTTP/2 protcol over a TLS connection.
 *   - UnencryptedHTTP2 is the HTTP/2 protocol over an unsecured TCP connection.
 */
export interface Protocols {
}
/**
 * PushOptions describes options for [Pusher.Push].
 */
export interface PushOptions {
  /**
   * Method specifies the HTTP method for the promised request.
   * If set, it must be "GET" or "HEAD". Empty means "GET".
   */
  Method: string;
  /**
   * Header specifies additional promised request headers. This cannot
   * include HTTP/2 pseudo header fields like ":path" and ":scheme",
   * which will be added automatically.
   */
  Header: Header;
}
/**
 * Pusher is the interface implemented by ResponseWriters that support
 * HTTP/2 server push. For more background, see
 * https://tools.ietf.org/html/rfc7540#section-8.2.
 */
export type Pusher = any;
/**
 * HTTP2Config defines HTTP/2 configuration parameters common to
 * both [Transport] and [Server].
 */
export interface HTTP2Config {
  /**
   * MaxConcurrentStreams optionally specifies the number of
   * concurrent streams that a peer may have open at a time.
   * If zero, MaxConcurrentStreams defaults to at least 100.
   */
  MaxConcurrentStreams: number /* int */;
  /**
   * MaxDecoderHeaderTableSize optionally specifies an upper limit for the
   * size of the header compression table used for decoding headers sent
   * by the peer.
   * A valid value is less than 4MiB.
   * If zero or invalid, a default value is used.
   */
  MaxDecoderHeaderTableSize: number /* int */;
  /**
   * MaxEncoderHeaderTableSize optionally specifies an upper limit for the
   * header compression table used for sending headers to the peer.
   * A valid value is less than 4MiB.
   * If zero or invalid, a default value is used.
   */
  MaxEncoderHeaderTableSize: number /* int */;
  /**
   * MaxReadFrameSize optionally specifies the largest frame
   * this endpoint is willing to read.
   * A valid value is between 16KiB and 16MiB, inclusive.
   * If zero or invalid, a default value is used.
   */
  MaxReadFrameSize: number /* int */;
  /**
   * MaxReceiveBufferPerConnection is the maximum size of the
   * flow control window for data received on a connection.
   * A valid value is at least 64KiB and less than 4MiB.
   * If invalid, a default value is used.
   */
  MaxReceiveBufferPerConnection: number /* int */;
  /**
   * MaxReceiveBufferPerStream is the maximum size of
   * the flow control window for data received on a stream (request).
   * A valid value is less than 4MiB.
   * If zero or invalid, a default value is used.
   */
  MaxReceiveBufferPerStream: number /* int */;
  /**
   * SendPingTimeout is the timeout after which a health check using a ping
   * frame will be carried out if no frame is received on a connection.
   * If zero, no health check is performed.
   */
  SendPingTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * PingTimeout is the timeout after which a connection will be closed
   * if a response to a ping is not received.
   * If zero, a default of 15 seconds is used.
   */
  PingTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * WriteByteTimeout is the timeout after which a connection will be
   * closed if no data can be written to it. The timeout begins when data is
   * available to write, and is extended whenever any bytes are written.
   */
  WriteByteTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * PermitProhibitedCipherSuites, if true, permits the use of
   * cipher suites prohibited by the HTTP/2 spec.
   */
  PermitProhibitedCipherSuites: boolean;
  /**
   * CountError, if non-nil, is called on HTTP/2 errors.
   * It is intended to increment a metric for monitoring.
   * The errType contains only lowercase letters, digits, and underscores
   * (a-z, 0-9, _).
   */
  CountError: any;
}

//////////
// source: jar.go

/**
 * A CookieJar manages storage and use of cookies in HTTP requests.
 * Implementations of CookieJar must be safe for concurrent use by multiple
 * goroutines.
 * The net/http/cookiejar package provides a CookieJar implementation.
 */
export type CookieJar = any;

//////////
// source: mapping.go


//////////
// source: method.go

/**
 * Common HTTP methods.
 * Unless otherwise noted, these are defined in RFC 7231 section 4.3.
 */
export const MethodGet = "GET";
/**
 * Common HTTP methods.
 * Unless otherwise noted, these are defined in RFC 7231 section 4.3.
 */
export const MethodHead = "HEAD";
/**
 * Common HTTP methods.
 * Unless otherwise noted, these are defined in RFC 7231 section 4.3.
 */
export const MethodPost = "POST";
/**
 * Common HTTP methods.
 * Unless otherwise noted, these are defined in RFC 7231 section 4.3.
 */
export const MethodPut = "PUT";
/**
 * Common HTTP methods.
 * Unless otherwise noted, these are defined in RFC 7231 section 4.3.
 */
export const MethodPatch = "PATCH"; // RFC 5789
/**
 * Common HTTP methods.
 * Unless otherwise noted, these are defined in RFC 7231 section 4.3.
 */
export const MethodDelete = "DELETE";
/**
 * Common HTTP methods.
 * Unless otherwise noted, these are defined in RFC 7231 section 4.3.
 */
export const MethodConnect = "CONNECT";
/**
 * Common HTTP methods.
 * Unless otherwise noted, these are defined in RFC 7231 section 4.3.
 */
export const MethodOptions = "OPTIONS";
/**
 * Common HTTP methods.
 * Unless otherwise noted, these are defined in RFC 7231 section 4.3.
 */
export const MethodTrace = "TRACE";

//////////
// source: pattern.go


//////////
// source: request.go

/**
 * ProtocolError represents an HTTP protocol error.
 * Deprecated: Not all errors in the http package related to protocol errors
 * are of type ProtocolError.
 */
export interface ProtocolError {
  ErrorString: string;
}
/**
 * A Request represents an HTTP request received by a server
 * or to be sent by a client.
 * The field semantics differ slightly between client and server
 * usage. In addition to the notes on the fields below, see the
 * documentation for [Request.Write] and [RoundTripper].
 */
export interface Request {
  /**
   * Method specifies the HTTP method (GET, POST, PUT, etc.).
   * For client requests, an empty string means GET.
   */
  Method: string;
  /**
   * URL specifies either the URI being requested (for server
   * requests) or the URL to access (for client requests).
   * For server requests, the URL is parsed from the URI
   * supplied on the Request-Line as stored in RequestURI.  For
   * most requests, fields other than Path and RawQuery will be
   * empty. (See RFC 7230, Section 5.3)
   * For client requests, the URL's Host specifies the server to
   * connect to, while the Request's Host field optionally
   * specifies the Host header value to send in the HTTP
   * request.
   */
  URL?: any /* url.URL */;
  /**
   * The protocol version for incoming server requests.
   * For client requests, these fields are ignored. The HTTP
   * client code always uses either HTTP/1.1 or HTTP/2.
   * See the docs on Transport for details.
   */
  Proto: string; // "HTTP/1.0"
  ProtoMajor: number /* int */; // 1
  ProtoMinor: number /* int */; // 0
  /**
   * Header contains the request header fields either received
   * by the server or to be sent by the client.
   * If a server received a request with header lines,
   * 	Host: example.com
   * 	accept-encoding: gzip, deflate
   * 	Accept-Language: en-us
   * 	fOO: Bar
   * 	foo: two
   * then
   * 	Header = map[string][]string{
   * 		"Accept-Encoding": {"gzip, deflate"},
   * 		"Accept-Language": {"en-us"},
   * 		"Foo": {"Bar", "two"},
   * 	}
   * For incoming requests, the Host header is promoted to the
   * Request.Host field and removed from the Header map.
   * HTTP defines that header names are case-insensitive. The
   * request parser implements this by using CanonicalHeaderKey,
   * making the first character and any characters following a
   * hyphen uppercase and the rest lowercase.
   * For client requests, certain headers such as Content-Length
   * and Connection are automatically written when needed and
   * values in Header may be ignored. See the documentation
   * for the Request.Write method.
   */
  Header: Header;
  /**
   * Body is the request's body.
   * For client requests, a nil body means the request has no
   * body, such as a GET request. The HTTP Client's Transport
   * is responsible for calling the Close method.
   * For server requests, the Request Body is always non-nil
   * but will return EOF immediately when no body is present.
   * The Server will close the request body. The ServeHTTP
   * Handler does not need to.
   * Body must allow Read to be called concurrently with Close.
   * In particular, calling Close should unblock a Read waiting
   * for input.
   */
  Body: any /* io.ReadCloser */;
  /**
   * GetBody defines an optional func to return a new copy of
   * Body. It is used for client requests when a redirect requires
   * reading the body more than once. Use of GetBody still
   * requires setting Body.
   * For server requests, it is unused.
   */
  GetBody: any;
  /**
   * ContentLength records the length of the associated content.
   * The value -1 indicates that the length is unknown.
   * Values >= 0 indicate that the given number of bytes may
   * be read from Body.
   * For client requests, a value of 0 with a non-nil Body is
   * also treated as unknown.
   */
  ContentLength: number /* int64 */;
  /**
   * TransferEncoding lists the transfer encodings from outermost to
   * innermost. An empty list denotes the "identity" encoding.
   * TransferEncoding can usually be ignored; chunked encoding is
   * automatically added and removed as necessary when sending and
   * receiving requests.
   */
  TransferEncoding: string[];
  /**
   * Close indicates whether to close the connection after
   * replying to this request (for servers) or after sending this
   * request and reading its response (for clients).
   * For server requests, the HTTP server handles this automatically
   * and this field is not needed by Handlers.
   * For client requests, setting this field prevents re-use of
   * TCP connections between requests to the same hosts, as if
   * Transport.DisableKeepAlives were set.
   */
  Close: boolean;
  /**
   * For server requests, Host specifies the host on which the
   * URL is sought. For HTTP/1 (per RFC 7230, section 5.4), this
   * is either the value of the "Host" header or the host name
   * given in the URL itself. For HTTP/2, it is the value of the
   * ":authority" pseudo-header field.
   * It may be of the form "host:port". For international domain
   * names, Host may be in Punycode or Unicode form. Use
   * golang.org/x/net/idna to convert it to either format if
   * needed.
   * To prevent DNS rebinding attacks, server Handlers should
   * validate that the Host header has a value for which the
   * Handler considers itself authoritative. The included
   * ServeMux supports patterns registered to particular host
   * names and thus protects its registered Handlers.
   * For client requests, Host optionally overrides the Host
   * header to send. If empty, the Request.Write method uses
   * the value of URL.Host. Host may contain an international
   * domain name.
   */
  Host: string;
  /**
   * Form contains the parsed form data, including both the URL
   * field's query parameters and the PATCH, POST, or PUT form data.
   * This field is only available after ParseForm is called.
   * The HTTP client ignores Form and uses Body instead.
   */
  Form: any /* url.Values */;
  /**
   * PostForm contains the parsed form data from PATCH, POST
   * or PUT body parameters.
   * This field is only available after ParseForm is called.
   * The HTTP client ignores PostForm and uses Body instead.
   */
  PostForm: any /* url.Values */;
  /**
   * MultipartForm is the parsed multipart form, including file uploads.
   * This field is only available after ParseMultipartForm is called.
   * The HTTP client ignores MultipartForm and uses Body instead.
   */
  MultipartForm?: any /* multipart.Form */;
  /**
   * Trailer specifies additional headers that are sent after the request
   * body.
   * For server requests, the Trailer map initially contains only the
   * trailer keys, with nil values. (The client declares which trailers it
   * will later send.)  While the handler is reading from Body, it must
   * not reference Trailer. After reading from Body returns EOF, Trailer
   * can be read again and will contain non-nil values, if they were sent
   * by the client.
   * For client requests, Trailer must be initialized to a map containing
   * the trailer keys to later send. The values may be nil or their final
   * values. The ContentLength must be 0 or -1, to send a chunked request.
   * After the HTTP request is sent the map values can be updated while
   * the request body is read. Once the body returns EOF, the caller must
   * not mutate Trailer.
   * Few HTTP clients, servers, or proxies support HTTP trailers.
   */
  Trailer: Header;
  /**
   * RemoteAddr allows HTTP servers and other software to record
   * the network address that sent the request, usually for
   * logging. This field is not filled in by ReadRequest and
   * has no defined format. The HTTP server in this package
   * sets RemoteAddr to an "IP:port" address before invoking a
   * handler.
   * This field is ignored by the HTTP client.
   */
  RemoteAddr: string;
  /**
   * RequestURI is the unmodified request-target of the
   * Request-Line (RFC 7230, Section 3.1.1) as sent by the client
   * to a server. Usually the URL field should be used instead.
   * It is an error to set this field in an HTTP client request.
   */
  RequestURI: string;
  /**
   * TLS allows HTTP servers and other software to record
   * information about the TLS connection on which the request
   * was received. This field is not filled in by ReadRequest.
   * The HTTP server in this package sets the field for
   * TLS-enabled connections before invoking a handler;
   * otherwise it leaves the field nil.
   * This field is ignored by the HTTP client.
   */
  TLS?: any /* tls.ConnectionState */;
  /**
   * Cancel is an optional channel whose closure indicates that the client
   * request should be regarded as canceled. Not all implementations of
   * RoundTripper may support Cancel.
   * For server requests, this field is not applicable.
   * Deprecated: Set the Request's context with NewRequestWithContext
   * instead. If a Request's Cancel field and context are both
   * set, it is undefined whether Cancel is respected.
   */
  Cancel: any;
  /**
   * Response is the redirect response which caused this request
   * to be created. This field is only populated during client
   * redirects.
   */
  Response?: Response;
  /**
   * Pattern is the [ServeMux] pattern that matched the request.
   * It is empty if the request was not matched against a pattern.
   */
  Pattern: string;
}
/**
 * MaxBytesError is returned by [MaxBytesReader] when its read limit is exceeded.
 */
export interface MaxBytesError {
  Limit: number /* int64 */;
}

//////////
// source: response.go

/**
 * Response represents the response from an HTTP request.
 * The [Client] and [Transport] return Responses from servers once
 * the response headers have been received. The response body
 * is streamed on demand as the Body field is read.
 */
export interface Response {
  Status: string; // e.g. "200 OK"
  StatusCode: number /* int */; // e.g. 200
  Proto: string; // e.g. "HTTP/1.0"
  ProtoMajor: number /* int */; // e.g. 1
  ProtoMinor: number /* int */; // e.g. 0
  /**
   * Header maps header keys to values. If the response had multiple
   * headers with the same key, they may be concatenated, with comma
   * delimiters.  (RFC 7230, section 3.2.2 requires that multiple headers
   * be semantically equivalent to a comma-delimited sequence.) When
   * Header values are duplicated by other fields in this struct (e.g.,
   * ContentLength, TransferEncoding, Trailer), the field values are
   * authoritative.
   * Keys in the map are canonicalized (see CanonicalHeaderKey).
   */
  Header: Header;
  /**
   * Body represents the response body.
   * The response body is streamed on demand as the Body field
   * is read. If the network connection fails or the server
   * terminates the response, Body.Read calls return an error.
   * The http Client and Transport guarantee that Body is always
   * non-nil, even on responses without a body or responses with
   * a zero-length body. It is the caller's responsibility to
   * close Body. The default HTTP client's Transport may not
   * reuse HTTP/1.x "keep-alive" TCP connections if the Body is
   * not read to completion and closed.
   * The Body is automatically dechunked if the server replied
   * with a "chunked" Transfer-Encoding.
   * As of Go 1.12, the Body will also implement io.Writer
   * on a successful "101 Switching Protocols" response,
   * as used by WebSockets and HTTP/2's "h2c" mode.
   */
  Body: any /* io.ReadCloser */;
  /**
   * ContentLength records the length of the associated content. The
   * value -1 indicates that the length is unknown. Unless Request.Method
   * is "HEAD", values >= 0 indicate that the given number of bytes may
   * be read from Body.
   */
  ContentLength: number /* int64 */;
  /**
   * Contains transfer encodings from outer-most to inner-most. Value is
   * nil, means that "identity" encoding is used.
   */
  TransferEncoding: string[];
  /**
   * Close records whether the header directed that the connection be
   * closed after reading Body. The value is advice for clients: neither
   * ReadResponse nor Response.Write ever closes a connection.
   */
  Close: boolean;
  /**
   * Uncompressed reports whether the response was sent compressed but
   * was decompressed by the http package. When true, reading from
   * Body yields the uncompressed content instead of the compressed
   * content actually set from the server, ContentLength is set to -1,
   * and the "Content-Length" and "Content-Encoding" fields are deleted
   * from the responseHeader. To get the original response from
   * the server, set Transport.DisableCompression to true.
   */
  Uncompressed: boolean;
  /**
   * Trailer maps trailer keys to values in the same
   * format as Header.
   * The Trailer initially contains only nil values, one for
   * each key specified in the server's "Trailer" header
   * value. Those values are not added to Header.
   * Trailer must not be accessed concurrently with Read calls
   * on the Body.
   * After Body.Read has returned io.EOF, Trailer will contain
   * any trailer values sent by the server.
   */
  Trailer: Header;
  /**
   * Request is the request that was sent to obtain this Response.
   * Request's Body is nil (having already been consumed).
   * This is only populated for Client requests.
   */
  Request?: Request;
  /**
   * TLS contains information about the TLS connection on which the
   * response was received. It is nil for unencrypted responses.
   * The pointer is shared between responses and should not be
   * modified.
   */
  TLS?: any /* tls.ConnectionState */;
}

//////////
// source: responsecontroller.go

/**
 * A ResponseController is used by an HTTP handler to control the response.
 * A ResponseController may not be used after the [Handler.ServeHTTP] method has returned.
 */
export interface ResponseController {
}

//////////
// source: routing_index.go


//////////
// source: routing_tree.go


//////////
// source: servemux121.go


//////////
// source: server.go

/**
 * A Handler responds to an HTTP request.
 * [Handler.ServeHTTP] should write reply headers and data to the [ResponseWriter]
 * and then return. Returning signals that the request is finished; it
 * is not valid to use the [ResponseWriter] or read from the
 * [Request.Body] after or concurrently with the completion of the
 * ServeHTTP call.
 * Depending on the HTTP client software, HTTP protocol version, and
 * any intermediaries between the client and the Go server, it may not
 * be possible to read from the [Request.Body] after writing to the
 * [ResponseWriter]. Cautious handlers should read the [Request.Body]
 * first, and then reply.
 * Except for reading the body, handlers should not modify the
 * provided Request.
 * If ServeHTTP panics, the server (the caller of ServeHTTP) assumes
 * that the effect of the panic was isolated to the active request.
 * It recovers the panic, logs a stack trace to the server error log,
 * and either closes the network connection or sends an HTTP/2
 * RST_STREAM, depending on the HTTP protocol. To abort a handler so
 * the client sees an interrupted response but the server doesn't log
 * an error, panic with the value [ErrAbortHandler].
 */
export type Handler = any;
/**
 * A ResponseWriter interface is used by an HTTP handler to
 * construct an HTTP response.
 * A ResponseWriter may not be used after [Handler.ServeHTTP] has returned.
 */
export type ResponseWriter = any;
/**
 * The Flusher interface is implemented by ResponseWriters that allow
 * an HTTP handler to flush buffered data to the client.
 * The default HTTP/1.x and HTTP/2 [ResponseWriter] implementations
 * support [Flusher], but ResponseWriter wrappers may not. Handlers
 * should always test for this ability at runtime.
 * Note that even for ResponseWriters that support Flush,
 * if the client is connected through an HTTP proxy,
 * the buffered data may not reach the client until the response
 * completes.
 */
export type Flusher = any;
/**
 * The Hijacker interface is implemented by ResponseWriters that allow
 * an HTTP handler to take over the connection.
 * The default [ResponseWriter] for HTTP/1.x connections supports
 * Hijacker, but HTTP/2 connections intentionally do not.
 * ResponseWriter wrappers may also not support Hijacker. Handlers
 * should always test for this ability at runtime.
 */
export type Hijacker = any;
/**
 * The CloseNotifier interface is implemented by ResponseWriters which
 * allow detecting when the underlying connection has gone away.
 * This mechanism can be used to cancel long operations on the server
 * if the client has disconnected before the response is ready.
 * Deprecated: the CloseNotifier interface predates Go's context package.
 * New code should use [Request.Context] instead.
 */
export type CloseNotifier = any;
/**
 * TrailerPrefix is a magic prefix for [ResponseWriter.Header] map keys
 * that, if present, signals that the map entry is actually for
 * the response trailers, and not the response headers. The prefix
 * is stripped after the ServeHTTP call finishes and the values are
 * sent in the trailers.
 * This mechanism is intended only for trailers that are not known
 * prior to the headers being written. If the set of trailers is fixed
 * or known before the header is written, the normal Go trailers mechanism
 * is preferred:
 * 	https://pkg.go.dev/net/http#ResponseWriter
 * 	https://pkg.go.dev/net/http#example-ResponseWriter-Trailers
 */
export const TrailerPrefix = "Trailer:";
/**
 * DefaultMaxHeaderBytes is the maximum permitted size of the headers
 * in an HTTP request.
 * This can be overridden by setting [Server.MaxHeaderBytes].
 */
export const DefaultMaxHeaderBytes = 1 << 20; // 1 MB
/**
 * TimeFormat is the time format to use when generating times in HTTP
 * headers. It is like [time.RFC1123] but hard-codes GMT as the time
 * zone. The time being formatted must be in UTC for Format to
 * generate the correct format.
 * For parsing this time format, see [ParseTime].
 */
export const TimeFormat = "Mon, 02 Jan 2006 15:04:05 GMT";
/**
 * The HandlerFunc type is an adapter to allow the use of
 * ordinary functions as HTTP handlers. If f is a function
 * with the appropriate signature, HandlerFunc(f) is a
 * [Handler] that calls f.
 */
export type HandlerFunc = any;
/**
 * ServeMux is an HTTP request multiplexer.
 * It matches the URL of each incoming request against a list of registered
 * patterns and calls the handler for the pattern that
 * most closely matches the URL.
 * # Patterns
 * Patterns can match the method, host and path of a request.
 * Some examples:
 *   - "/index.html" matches the path "/index.html" for any host and method.
 *   - "GET /static/" matches a GET request whose path begins with "/static/".
 *   - "example.com/" matches any request to the host "example.com".
 *   - "example.com/{$}" matches requests with host "example.com" and path "/".
 *   - "/b/{bucket}/o/{objectname...}" matches paths whose first segment is "b"
 *     and whose third segment is "o". The name "bucket" denotes the second
 *     segment and "objectname" denotes the remainder of the path.
 * In general, a pattern looks like
 * 	[METHOD ][HOST]/[PATH]
 * All three parts are optional; "/" is a valid pattern.
 * If METHOD is present, it must be followed by at least one space or tab.
 * Literal (that is, non-wildcard) parts of a pattern match
 * the corresponding parts of a request case-sensitively.
 * A pattern with no method matches every method. A pattern
 * with the method GET matches both GET and HEAD requests.
 * Otherwise, the method must match exactly.
 * A pattern with no host matches every host.
 * A pattern with a host matches URLs on that host only.
 * A path can include wildcard segments of the form {NAME} or {NAME...}.
 * For example, "/b/{bucket}/o/{objectname...}".
 * The wildcard name must be a valid Go identifier.
 * Wildcards must be full path segments: they must be preceded by a slash and followed by
 * either a slash or the end of the string.
 * For example, "/b_{bucket}" is not a valid pattern.
 * Normally a wildcard matches only a single path segment,
 * ending at the next literal slash (not %2F) in the request URL.
 * But if the "..." is present, then the wildcard matches the remainder of the URL path, including slashes.
 * (Therefore it is invalid for a "..." wildcard to appear anywhere but at the end of a pattern.)
 * The match for a wildcard can be obtained by calling [Request.PathValue] with the wildcard's name.
 * A trailing slash in a path acts as an anonymous "..." wildcard.
 * The special wildcard {$} matches only the end of the URL.
 * For example, the pattern "/{$}" matches only the path "/",
 * whereas the pattern "/" matches every path.
 * For matching, both pattern paths and incoming request paths are unescaped segment by segment.
 * So, for example, the path "/a%2Fb/100%25" is treated as having two segments, "a/b" and "100%".
 * The pattern "/a%2fb/" matches it, but the pattern "/a/b/" does not.
 * # Precedence
 * If two or more patterns match a request, then the most specific pattern takes precedence.
 * A pattern P1 is more specific than P2 if P1 matches a strict subset of P2’s requests;
 * that is, if P2 matches all the requests of P1 and more.
 * If neither is more specific, then the patterns conflict.
 * There is one exception to this rule, for backwards compatibility:
 * if two patterns would otherwise conflict and one has a host while the other does not,
 * then the pattern with the host takes precedence.
 * If a pattern passed to [ServeMux.Handle] or [ServeMux.HandleFunc] conflicts with
 * another pattern that is already registered, those functions panic.
 * As an example of the general rule, "/images/thumbnails/" is more specific than "/images/",
 * so both can be registered.
 * The former matches paths beginning with "/images/thumbnails/"
 * and the latter will match any other path in the "/images/" subtree.
 * As another example, consider the patterns "GET /" and "/index.html":
 * both match a GET request for "/index.html", but the former pattern
 * matches all other GET and HEAD requests, while the latter matches any
 * request for "/index.html" that uses a different method.
 * The patterns conflict.
 * # Trailing-slash redirection
 * Consider a [ServeMux] with a handler for a subtree, registered using a trailing slash or "..." wildcard.
 * If the ServeMux receives a request for the subtree root without a trailing slash,
 * it redirects the request by adding the trailing slash.
 * This behavior can be overridden with a separate registration for the path without
 * the trailing slash or "..." wildcard. For example, registering "/images/" causes ServeMux
 * to redirect a request for "/images" to "/images/", unless "/images" has
 * been registered separately.
 * # Request sanitizing
 * ServeMux also takes care of sanitizing the URL request path and the Host
 * header, stripping the port number and redirecting any request containing . or
 * .. segments or repeated slashes to an equivalent, cleaner URL.
 * Escaped path elements such as "%2e" for "." and "%2f" for "/" are preserved
 * and aren't considered separators for request routing.
 * # Compatibility
 * The pattern syntax and matching behavior of ServeMux changed significantly
 * in Go 1.22. To restore the old behavior, set the GODEBUG environment variable
 * to "httpmuxgo121=1". This setting is read once, at program startup; changes
 * during execution will be ignored.
 * The backwards-incompatible changes include:
 *   - Wildcards are just ordinary literal path segments in 1.21.
 *     For example, the pattern "/{x}" will match only that path in 1.21,
 *     but will match any one-segment path in 1.22.
 *   - In 1.21, no pattern was rejected, unless it was empty or conflicted with an existing pattern.
 *     In 1.22, syntactically invalid patterns will cause [ServeMux.Handle] and [ServeMux.HandleFunc] to panic.
 *     For example, in 1.21, the patterns "/{"  and "/a{x}" match themselves,
 *     but in 1.22 they are invalid and will cause a panic when registered.
 *   - In 1.22, each segment of a pattern is unescaped; this was not done in 1.21.
 *     For example, in 1.22 the pattern "/%61" matches the path "/a" ("%61" being the URL escape sequence for "a"),
 *     but in 1.21 it would match only the path "/%2561" (where "%25" is the escape for the percent sign).
 *   - When matching patterns to paths, in 1.22 each segment of the path is unescaped; in 1.21, the entire path is unescaped.
 *     This change mostly affects how paths with %2F escapes adjacent to slashes are treated.
 *     See https://go.dev/issue/21955 for details.
 */
export interface ServeMux {
}
/**
 * A Server defines parameters for running an HTTP server.
 * The zero value for Server is a valid configuration.
 */
export interface Server {
  /**
   * Addr optionally specifies the TCP address for the server to listen on,
   * in the form "host:port". If empty, ":http" (port 80) is used.
   * The service names are defined in RFC 6335 and assigned by IANA.
   * See net.Dial for details of the address format.
   */
  Addr: string;
  Handler: Handler; // handler to invoke, http.DefaultServeMux if nil
  /**
   * DisableGeneralOptionsHandler, if true, passes "OPTIONS *" requests to the Handler,
   * otherwise responds with 200 OK and Content-Length: 0.
   */
  DisableGeneralOptionsHandler: boolean;
  /**
   * TLSConfig optionally provides a TLS configuration for use
   * by ServeTLS and ListenAndServeTLS. Note that this value is
   * cloned by ServeTLS and ListenAndServeTLS, so it's not
   * possible to modify the configuration with methods like
   * tls.Config.SetSessionTicketKeys. To use
   * SetSessionTicketKeys, use Server.Serve with a TLS Listener
   * instead.
   */
  TLSConfig?: any /* tls.Config */;
  /**
   * ReadTimeout is the maximum duration for reading the entire
   * request, including the body. A zero or negative value means
   * there will be no timeout.
   * Because ReadTimeout does not let Handlers make per-request
   * decisions on each request body's acceptable deadline or
   * upload rate, most users will prefer to use
   * ReadHeaderTimeout. It is valid to use them both.
   */
  ReadTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * ReadHeaderTimeout is the amount of time allowed to read
   * request headers. The connection's read deadline is reset
   * after reading the headers and the Handler can decide what
   * is considered too slow for the body. If zero, the value of
   * ReadTimeout is used. If negative, or if zero and ReadTimeout
   * is zero or negative, there is no timeout.
   */
  ReadHeaderTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * WriteTimeout is the maximum duration before timing out
   * writes of the response. It is reset whenever a new
   * request's header is read. Like ReadTimeout, it does not
   * let Handlers make decisions on a per-request basis.
   * A zero or negative value means there will be no timeout.
   */
  WriteTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * IdleTimeout is the maximum amount of time to wait for the
   * next request when keep-alives are enabled. If zero, the value
   * of ReadTimeout is used. If negative, or if zero and ReadTimeout
   * is zero or negative, there is no timeout.
   */
  IdleTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * MaxHeaderBytes controls the maximum number of bytes the
   * server will read parsing the request header's keys and
   * values, including the request line. It does not limit the
   * size of the request body.
   * If zero, DefaultMaxHeaderBytes is used.
   */
  MaxHeaderBytes: number /* int */;
  /**
   * TLSNextProto optionally specifies a function to take over
   * ownership of the provided TLS connection when an ALPN
   * protocol upgrade has occurred. The map key is the protocol
   * name negotiated. The Handler argument should be used to
   * handle HTTP requests and will initialize the Request's TLS
   * and RemoteAddr if not already set. The connection is
   * automatically closed when the function returns.
   * If TLSNextProto is not nil, HTTP/2 support is not enabled
   * automatically.
   */
  TLSNextProto: { [key: string]: any};
  /**
   * ConnState specifies an optional callback function that is
   * called when a client connection changes state. See the
   * ConnState type and associated constants for details.
   */
  ConnState: any;
  /**
   * ErrorLog specifies an optional logger for errors accepting
   * connections, unexpected behavior from handlers, and
   * underlying FileSystem errors.
   * If nil, logging is done via the log package's standard logger.
   */
  ErrorLog?: any /* log.Logger */;
  /**
   * BaseContext optionally specifies a function that returns
   * the base context for incoming requests on this server.
   * The provided Listener is the specific Listener that's
   * about to start accepting requests.
   * If BaseContext is nil, the default is context.Background().
   * If non-nil, it must return a non-nil context.
   */
  BaseContext: any;
  /**
   * ConnContext optionally specifies a function that modifies
   * the context used for a new connection c. The provided ctx
   * is derived from the base context and has a ServerContextKey
   * value.
   */
  ConnContext: any;
  /**
   * HTTP2 configures HTTP/2 connections.
   * This field does not yet have any effect.
   * See https://go.dev/issue/67813.
   */
  HTTP2?: HTTP2Config;
  /**
   * Protocols is the set of protocols accepted by the server.
   * If Protocols includes UnencryptedHTTP2, the server will accept
   * unencrypted HTTP/2 connections. The server can serve both
   * HTTP/1 and unencrypted HTTP/2 on the same address and port.
   * If Protocols is nil, the default is usually HTTP/1 and HTTP/2.
   * If TLSNextProto is non-nil and does not contain an "h2" entry,
   * the default is HTTP/1 only.
   */
  Protocols?: Protocols;
}
/**
 * A ConnState represents the state of a client connection to a server.
 * It's used by the optional [Server.ConnState] hook.
 */
export type ConnState = number /* int */;
/**
 * StateNew represents a new connection that is expected to
 * send a request immediately. Connections begin at this
 * state and then transition to either StateActive or
 * StateClosed.
 */
export const StateNew: ConnState = 0;
/**
 * StateActive represents a connection that has read 1 or more
 * bytes of a request. The Server.ConnState hook for
 * StateActive fires before the request has entered a handler
 * and doesn't fire again until the request has been
 * handled. After the request is handled, the state
 * transitions to StateClosed, StateHijacked, or StateIdle.
 * For HTTP/2, StateActive fires on the transition from zero
 * to one active request, and only transitions away once all
 * active requests are complete. That means that ConnState
 * cannot be used to do per-request work; ConnState only notes
 * the overall state of the connection.
 */
export const StateActive: ConnState = 1;
/**
 * StateIdle represents a connection that has finished
 * handling a request and is in the keep-alive state, waiting
 * for a new request. Connections transition from StateIdle
 * to either StateActive or StateClosed.
 */
export const StateIdle: ConnState = 2;
/**
 * StateHijacked represents a hijacked connection.
 * This is a terminal state. It does not transition to StateClosed.
 */
export const StateHijacked: ConnState = 3;
/**
 * StateClosed represents a closed connection.
 * This is a terminal state. Hijacked connections do not
 * transition to StateClosed.
 */
export const StateClosed: ConnState = 4;

//////////
// source: sniff.go


//////////
// source: socks_bundle.go


//////////
// source: status.go

/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusContinue = 100; // RFC 9110, 15.2.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusSwitchingProtocols = 101; // RFC 9110, 15.2.2
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusProcessing = 102; // RFC 2518, 10.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusEarlyHints = 103; // RFC 8297
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusOK = 200; // RFC 9110, 15.3.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusCreated = 201; // RFC 9110, 15.3.2
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusAccepted = 202; // RFC 9110, 15.3.3
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusNonAuthoritativeInfo = 203; // RFC 9110, 15.3.4
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusNoContent = 204; // RFC 9110, 15.3.5
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusResetContent = 205; // RFC 9110, 15.3.6
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusPartialContent = 206; // RFC 9110, 15.3.7
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusMultiStatus = 207; // RFC 4918, 11.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusAlreadyReported = 208; // RFC 5842, 7.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusIMUsed = 226; // RFC 3229, 10.4.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusMultipleChoices = 300; // RFC 9110, 15.4.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusMovedPermanently = 301; // RFC 9110, 15.4.2
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusFound = 302; // RFC 9110, 15.4.3
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusSeeOther = 303; // RFC 9110, 15.4.4
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusNotModified = 304; // RFC 9110, 15.4.5
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusUseProxy = 305; // RFC 9110, 15.4.6
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusTemporaryRedirect = 307; // RFC 9110, 15.4.8
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusPermanentRedirect = 308; // RFC 9110, 15.4.9
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusBadRequest = 400; // RFC 9110, 15.5.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusUnauthorized = 401; // RFC 9110, 15.5.2
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusPaymentRequired = 402; // RFC 9110, 15.5.3
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusForbidden = 403; // RFC 9110, 15.5.4
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusNotFound = 404; // RFC 9110, 15.5.5
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusMethodNotAllowed = 405; // RFC 9110, 15.5.6
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusNotAcceptable = 406; // RFC 9110, 15.5.7
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusProxyAuthRequired = 407; // RFC 9110, 15.5.8
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusRequestTimeout = 408; // RFC 9110, 15.5.9
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusConflict = 409; // RFC 9110, 15.5.10
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusGone = 410; // RFC 9110, 15.5.11
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusLengthRequired = 411; // RFC 9110, 15.5.12
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusPreconditionFailed = 412; // RFC 9110, 15.5.13
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusRequestEntityTooLarge = 413; // RFC 9110, 15.5.14
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusRequestURITooLong = 414; // RFC 9110, 15.5.15
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusUnsupportedMediaType = 415; // RFC 9110, 15.5.16
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusRequestedRangeNotSatisfiable = 416; // RFC 9110, 15.5.17
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusExpectationFailed = 417; // RFC 9110, 15.5.18
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusTeapot = 418; // RFC 9110, 15.5.19 (Unused)
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusMisdirectedRequest = 421; // RFC 9110, 15.5.20
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusUnprocessableEntity = 422; // RFC 9110, 15.5.21
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusLocked = 423; // RFC 4918, 11.3
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusFailedDependency = 424; // RFC 4918, 11.4
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusTooEarly = 425; // RFC 8470, 5.2.
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusUpgradeRequired = 426; // RFC 9110, 15.5.22
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusPreconditionRequired = 428; // RFC 6585, 3
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusTooManyRequests = 429; // RFC 6585, 4
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusRequestHeaderFieldsTooLarge = 431; // RFC 6585, 5
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusUnavailableForLegalReasons = 451; // RFC 7725, 3
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusInternalServerError = 500; // RFC 9110, 15.6.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusNotImplemented = 501; // RFC 9110, 15.6.2
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusBadGateway = 502; // RFC 9110, 15.6.3
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusServiceUnavailable = 503; // RFC 9110, 15.6.4
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusGatewayTimeout = 504; // RFC 9110, 15.6.5
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusHTTPVersionNotSupported = 505; // RFC 9110, 15.6.6
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusVariantAlsoNegotiates = 506; // RFC 2295, 8.1
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusInsufficientStorage = 507; // RFC 4918, 11.5
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusLoopDetected = 508; // RFC 5842, 7.2
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusNotExtended = 510; // RFC 2774, 7
/**
 * HTTP status codes as registered with IANA.
 * See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export const StatusNetworkAuthenticationRequired = 511; // RFC 6585, 6

//////////
// source: transfer.go


//////////
// source: transport.go

/**
 * DefaultMaxIdleConnsPerHost is the default value of [Transport]'s
 * MaxIdleConnsPerHost.
 */
export const DefaultMaxIdleConnsPerHost = 2;
/**
 * Transport is an implementation of [RoundTripper] that supports HTTP,
 * HTTPS, and HTTP proxies (for either HTTP or HTTPS with CONNECT).
 * By default, Transport caches connections for future re-use.
 * This may leave many open connections when accessing many hosts.
 * This behavior can be managed using [Transport.CloseIdleConnections] method
 * and the [Transport.MaxIdleConnsPerHost] and [Transport.DisableKeepAlives] fields.
 * Transports should be reused instead of created as needed.
 * Transports are safe for concurrent use by multiple goroutines.
 * A Transport is a low-level primitive for making HTTP and HTTPS requests.
 * For high-level functionality, such as cookies and redirects, see [Client].
 * Transport uses HTTP/1.1 for HTTP URLs and either HTTP/1.1 or HTTP/2
 * for HTTPS URLs, depending on whether the server supports HTTP/2,
 * and how the Transport is configured. The [DefaultTransport] supports HTTP/2.
 * To explicitly enable HTTP/2 on a transport, set [Transport.Protocols].
 * Responses with status codes in the 1xx range are either handled
 * automatically (100 expect-continue) or ignored. The one
 * exception is HTTP status code 101 (Switching Protocols), which is
 * considered a terminal status and returned by [Transport.RoundTrip]. To see the
 * ignored 1xx responses, use the httptrace trace package's
 * ClientTrace.Got1xxResponse.
 * Transport only retries a request upon encountering a network error
 * if the connection has been already been used successfully and if the
 * request is idempotent and either has no body or has its [Request.GetBody]
 * defined. HTTP requests are considered idempotent if they have HTTP methods
 * GET, HEAD, OPTIONS, or TRACE; or if their [Header] map contains an
 * "Idempotency-Key" or "X-Idempotency-Key" entry. If the idempotency key
 * value is a zero-length slice, the request is treated as idempotent but the
 * header is not sent on the wire.
 */
export interface Transport {
  /**
   * Proxy specifies a function to return a proxy for a given
   * Request. If the function returns a non-nil error, the
   * request is aborted with the provided error.
   * The proxy type is determined by the URL scheme. "http",
   * "https", "socks5", and "socks5h" are supported. If the scheme is empty,
   * "http" is assumed.
   * "socks5" is treated the same as "socks5h".
   * If the proxy URL contains a userinfo subcomponent,
   * the proxy request will pass the username and password
   * in a Proxy-Authorization header.
   * If Proxy is nil or returns a nil *URL, no proxy is used.
   */
  Proxy: any;
  /**
   * OnProxyConnectResponse is called when the Transport gets an HTTP response from
   * a proxy for a CONNECT request. It's called before the check for a 200 OK response.
   * If it returns an error, the request fails with that error.
   */
  OnProxyConnectResponse: any;
  /**
   * DialContext specifies the dial function for creating unencrypted TCP connections.
   * If DialContext is nil (and the deprecated Dial below is also nil),
   * then the transport dials using package net.
   * DialContext runs concurrently with calls to RoundTrip.
   * A RoundTrip call that initiates a dial may end up using
   * a connection dialed previously when the earlier connection
   * becomes idle before the later DialContext completes.
   */
  DialContext: any;
  /**
   * Dial specifies the dial function for creating unencrypted TCP connections.
   * Dial runs concurrently with calls to RoundTrip.
   * A RoundTrip call that initiates a dial may end up using
   * a connection dialed previously when the earlier connection
   * becomes idle before the later Dial completes.
   * Deprecated: Use DialContext instead, which allows the transport
   * to cancel dials as soon as they are no longer needed.
   * If both are set, DialContext takes priority.
   */
  Dial: any;
  /**
   * DialTLSContext specifies an optional dial function for creating
   * TLS connections for non-proxied HTTPS requests.
   * If DialTLSContext is nil (and the deprecated DialTLS below is also nil),
   * DialContext and TLSClientConfig are used.
   * If DialTLSContext is set, the Dial and DialContext hooks are not used for HTTPS
   * requests and the TLSClientConfig and TLSHandshakeTimeout
   * are ignored. The returned net.Conn is assumed to already be
   * past the TLS handshake.
   */
  DialTLSContext: any;
  /**
   * DialTLS specifies an optional dial function for creating
   * TLS connections for non-proxied HTTPS requests.
   * Deprecated: Use DialTLSContext instead, which allows the transport
   * to cancel dials as soon as they are no longer needed.
   * If both are set, DialTLSContext takes priority.
   */
  DialTLS: any;
  /**
   * TLSClientConfig specifies the TLS configuration to use with
   * tls.Client.
   * If nil, the default configuration is used.
   * If non-nil, HTTP/2 support may not be enabled by default.
   */
  TLSClientConfig?: any /* tls.Config */;
  /**
   * TLSHandshakeTimeout specifies the maximum amount of time to
   * wait for a TLS handshake. Zero means no timeout.
   */
  TLSHandshakeTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * DisableKeepAlives, if true, disables HTTP keep-alives and
   * will only use the connection to the server for a single
   * HTTP request.
   * This is unrelated to the similarly named TCP keep-alives.
   */
  DisableKeepAlives: boolean;
  /**
   * DisableCompression, if true, prevents the Transport from
   * requesting compression with an "Accept-Encoding: gzip"
   * request header when the Request contains no existing
   * Accept-Encoding value. If the Transport requests gzip on
   * its own and gets a gzipped response, it's transparently
   * decoded in the Response.Body. However, if the user
   * explicitly requested gzip it is not automatically
   * uncompressed.
   */
  DisableCompression: boolean;
  /**
   * MaxIdleConns controls the maximum number of idle (keep-alive)
   * connections across all hosts. Zero means no limit.
   */
  MaxIdleConns: number /* int */;
  /**
   * MaxIdleConnsPerHost, if non-zero, controls the maximum idle
   * (keep-alive) connections to keep per-host. If zero,
   * DefaultMaxIdleConnsPerHost is used.
   */
  MaxIdleConnsPerHost: number /* int */;
  /**
   * MaxConnsPerHost optionally limits the total number of
   * connections per host, including connections in the dialing,
   * active, and idle states. On limit violation, dials will block.
   * Zero means no limit.
   */
  MaxConnsPerHost: number /* int */;
  /**
   * IdleConnTimeout is the maximum amount of time an idle
   * (keep-alive) connection will remain idle before closing
   * itself.
   * Zero means no limit.
   */
  IdleConnTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * ResponseHeaderTimeout, if non-zero, specifies the amount of
   * time to wait for a server's response headers after fully
   * writing the request (including its body, if any). This
   * time does not include the time to read the response body.
   */
  ResponseHeaderTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * ExpectContinueTimeout, if non-zero, specifies the amount of
   * time to wait for a server's first response headers after fully
   * writing the request headers if the request has an
   * "Expect: 100-continue" header. Zero means no timeout and
   * causes the body to be sent immediately, without
   * waiting for the server to approve.
   * This time does not include the time to send the request header.
   */
  ExpectContinueTimeout: number /* time in nanoseconds (time.Duration) */;
  /**
   * TLSNextProto specifies how the Transport switches to an
   * alternate protocol (such as HTTP/2) after a TLS ALPN
   * protocol negotiation. If Transport dials a TLS connection
   * with a non-empty protocol name and TLSNextProto contains a
   * map entry for that key (such as "h2"), then the func is
   * called with the request's authority (such as "example.com"
   * or "example.com:1234") and the TLS connection. The function
   * must return a RoundTripper that then handles the request.
   * If TLSNextProto is not nil, HTTP/2 support is not enabled
   * automatically.
   */
  TLSNextProto: { [key: string]: any};
  /**
   * ProxyConnectHeader optionally specifies headers to send to
   * proxies during CONNECT requests.
   * To set the header dynamically, see GetProxyConnectHeader.
   */
  ProxyConnectHeader: Header;
  /**
   * GetProxyConnectHeader optionally specifies a func to return
   * headers to send to proxyURL during a CONNECT request to the
   * ip:port target.
   * If it returns an error, the Transport's RoundTrip fails with
   * that error. It can return (nil, nil) to not add headers.
   * If GetProxyConnectHeader is non-nil, ProxyConnectHeader is
   * ignored.
   */
  GetProxyConnectHeader: any;
  /**
   * MaxResponseHeaderBytes specifies a limit on how many
   * response bytes are allowed in the server's response
   * header.
   * Zero means to use a default limit.
   */
  MaxResponseHeaderBytes: number /* int64 */;
  /**
   * WriteBufferSize specifies the size of the write buffer used
   * when writing to the transport.
   * If zero, a default (currently 4KB) is used.
   */
  WriteBufferSize: number /* int */;
  /**
   * ReadBufferSize specifies the size of the read buffer used
   * when reading from the transport.
   * If zero, a default (currently 4KB) is used.
   */
  ReadBufferSize: number /* int */;
  /**
   * ForceAttemptHTTP2 controls whether HTTP/2 is enabled when a non-zero
   * Dial, DialTLS, or DialContext func or TLSClientConfig is provided.
   * By default, use of any those fields conservatively disables HTTP/2.
   * To use a custom dialer or TLS config and still attempt HTTP/2
   * upgrades, set this to true.
   */
  ForceAttemptHTTP2: boolean;
  /**
   * HTTP2 configures HTTP/2 connections.
   * This field does not yet have any effect.
   * See https://go.dev/issue/67813.
   */
  HTTP2?: HTTP2Config;
  /**
   * Protocols is the set of protocols supported by the transport.
   * If Protocols includes UnencryptedHTTP2 and does not include HTTP1,
   * the transport will use unencrypted HTTP/2 for requests for http:// URLs.
   * If Protocols is nil, the default is usually HTTP/1 only.
   * If ForceAttemptHTTP2 is true, or if TLSNextProto contains an "h2" entry,
   * the default is HTTP/1 and HTTP/2.
   */
  Protocols?: Protocols;
}
